### Testar a raiz da aplicação

GET http://localhost:5248

### Listar Produtos

GET http://localhost:5248/produto/listar

### Cadastrar Produto

POST http://localhost:5248/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Bolacha",
    "preco": 4.5,
    "quantidade" : 156
}

### Remover Produto
